version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  doodleback:
    build : ./api/
    ports:
      - "8080:8080"
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
  doodlefront: 
    build: 
      context: ./front/
      dockerfile: Dockerfile
      target : prod
    ports:
      - 80:8080
    volumes:
      - ./api/server-confs:/server-confs:ro
  myadmin:
    image : phpmyadmin
    ports:
      - "8082:80"
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"





