global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'back'
    static_configs:
      - targets: ['doodleback:8080']
  
