apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-keycloack
  name: mysql-keycloack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-keycloack
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-keycloack
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: keycloak
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: keycloak
          image: mysql:5.7
          name: mysql-keycloack
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-keycloack-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-keycloack-claim0
          persistentVolumeClaim:
            claimName: mysql-keycloack-claim0
status: {}
